In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [4]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [6]:
df.Cabin.value_counts()

B96 B98        4
G6             4
C23 C25 C27    4
C22 C26        3
F33            3
              ..
E34            1
C7             1
C54            1
E36            1
C148           1
Name: Cabin, Length: 147, dtype: int64

In [7]:
df.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [8]:
df.Age.fillna(df.Age.mean(), inplace=True)

In [9]:
df.Cabin.fillna('B96 B98', inplace=True)

In [10]:
df.Embarked.fillna('S', inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object 
 11  Embarked     891 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
lc_ohe = LabelEncoder() 

In [15]:
# Name	Sex	 Cabin	Embarked >> Columns to encode

In [16]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare    Cabin Embarked  
0      0  A/5 21171   7.2500  B96 B98        S  
1      0   PC 17599  71.2833      C85        C

In [17]:
df['Name_en'] = lc_ohe.fit_transform(df.Name)
df['Sex_en'] = lc_ohe.fit_transform(df.Sex)
df['Cabin_en'] = lc_ohe.fit_transform(df.Cabin)
df['Embarked_en'] = lc_ohe.fit_transform(df.Embarked)
df['Ticket_en'] = lc_ohe.fit_transform(df.Ticket)

In [18]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare    Cabin Embarked  Name_en  Sex_en  Cabin_en  \
0      0  A/5 21171   7.2500  B96 B98        S      108       1        47   
1      0   PC 17599  71.2833      C85        C      190       0        81   

   Embarked_en  Ticket_en  
0            2        523  
1            0        596

In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
dTree = DecisionTreeClassifier()

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
df = df.drop(['Name','Sex', 'Embarked','Cabin', 'Ticket'], axis=1)

In [23]:
df.head(2)

PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Name_en  \
0            1         0       3  22.0      1      0   7.2500      108   
1            2         1       1  38.0      1      0  71.2833      190   

   Sex_en  Cabin_en  Embarked_en  Ticket_en  
0       1        47            2        523  
1       0        81            0        596

In [24]:
X = df.drop(['Survived'], axis = 1)

Y = df.Survived

In [25]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, train_size = 0.75)

In [26]:
dTree.fit(x_train, y_train)

DecisionTreeClassifier()

In [27]:
y_pred = dTree.predict(x_test)

In [28]:
y_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0], dtype=int64)

In [29]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.81      0.79       134
           1       0.68      0.63      0.65        89

    accuracy                           0.74       223
   macro avg       0.72      0.72      0.72       223
weighted avg       0.73      0.74      0.73       223



In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
print(confusion_matrix(y_test, y_pred))

[[108  26]
 [ 33  56]]


In [33]:
from sklearn.metrics import accuracy_score

In [34]:
print(accuracy_score(y_test, y_pred))

0.7354260089686099


In [35]:
df

PassengerId  Survived  Pclass        Age  SibSp  Parch     Fare  Name_en  \
0              1         0       3  22.000000      1      0   7.2500      108   
1              2         1       1  38.000000      1      0  71.2833      190   
2              3         1       3  26.000000      0      0   7.9250      353   
3              4         1       1  35.000000      1      0  53.1000      272   
4              5         0       3  35.000000      0      0   8.0500       15   
..           ...       ...     ...        ...    ...    ...      ...      ...   
886          887         0       2  27.000000      0      0  13.0000      548   
887          888         1       1  19.000000      0      0  30.0000      303   
888          889         0       3  29.699118      1      2  23.4500      413   
889          890         1       1  26.000000      0      0  30.0000       81   
890          891         0       3  32.000000      0      0   7.7500      220   

     Sex_en  Cabin_en  Embarked_en  Ticket_en  
0         1        47            2        523  
1         0        81            0        596  
2         0        47            2        669  
3         0        55            2         49  
4         1        47            2        472  
..      ...       ...          ...        ...  
886       1        47            2        101  
887       0        30            2         14  
888       0        47            2        675  
889       1        60            0          8  
890       1        47            1        466  

[891 rows x 12 columns]

In [37]:
dTree.predict([[1,3,22.000000,1,0,7.2500,108,1,47,2,523]])

C:\Users\abdul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [38]:
dTree.predict([[4,1,35.000000,1,0,53.1000,272,0,55,2,49]])

C:\Users\abdul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [39]:
dTree.predict([[887,2,27.000000,0,0,13.0000,548,1,47,2,101]])

C:\Users\abdul\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [40]:
# Done Our model predict 2 right out of 3. Testing accuracy will be 0.66664 or 66.664% or 67%. 